name: $(Rev:r)
jobs:
- job: build
  strategy:
    matrix:
      Windows:
        vmImage: 'windows-latest'
      Linux:
        vmImage: 'ubuntu-latest'
      MacOS:
        vmImage: 'macOS-latest'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: dotnet build build.proj
    displayName: dotnet build build.proj
    env:
      BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
      BUILD_ID: $(BUILD.BUILDNUMBER)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'nupkgs'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
